### PR TITLE
refactor: skeleton loading state updates

### PR DESCRIPTION
**Pull request by alexbarnsley**
## Summary

https://app.clickup.com/t/862jzw28y

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
some general remarks on this:
- the loading state rows are not the same size as the actual rows, causing a shift once the data loads (tested on transactions table, desktop)
- on mobile some tables have columns that span two rows, the loading states do not account for this (tested on transactions table, 1024px)
- on mobile there is also a slight shift, probably due to the badges taking up more space than the text (tested on transactions table, < 640px)
- top accounts address loading state is very short while the address there is shown in full most of the time

although most remarks mention transaction table, it applies to all tables that span more rows etc

**Comment by alexbarnsley** [comment]
Will have a looksee @ItsANameToo, thanks

**Comment by alexbarnsley** [comment]
I think I've covered all tables including responsiveness @ItsANameToo, if you could have a gander please

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
just minor remarks really:
- delegate page - delegates table - 768-1024 has a slight shift in row height between skeleton and actual data
- delegate page - missed blocks table - 640-768 lacks the skeleton elements for the entries (only the "header" shows). Seems to be using the mobile skeleton from < 640
- top accounts - 768-1024 is missing the second row for the percentage in the loading state
- top accounts - 640-768 has the address skeleton aligned on the right while the value shows on the left after loading. Likewise for < 640

**Comment by ItsANameToo** [comment]
I ignored the delegate monitor as that will see some changes soon

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
