### PR TITLE
refactor: mainsail monitor show overflow forgers

### PR DESCRIPTION
**Pull request by alexbarnsley**
## Summary

https://app.clickup.com/t/86dtvhxfn

todo:

- [x] add additional validator(s) when a overflow validators miss forging
- [x] look into time until forge
- [x] additional tests
- [x] phpstan?
- [x] Look into why it's not showing as pending in the attached screenshot
- [x] Add comments to new methods

Also includes a caching fix when fetching last blocks for validators

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
When a block gets missed (at least that's what I think causes it) it seems the Time to Forge text duplicates as shown in the image below. Can you check that you see the same thing as me please when you next get chance. 

image

**Comment by alexbarnsley** [comment]
Should be sorted @samharperpittam

**Comment by alexbarnsley** [comment]
image

Look into why it's not showing as pending in the above screenshot

--------------------

add comments to some of the newer methods to detail what they're doing

**Comment by alexbarnsley** [comment]
Date of overflow is way off

image

**Review by samharperpittam — APPROVED** [review]

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
