### PR TITLE
feat: blocks websocket reloading

### PR DESCRIPTION
**Pull request by alexbarnsley**
## Summary

https://app.clickup.com/t/86dqjdxjm
https://app.clickup.com/t/86dtgqabj

Requires https://github.com/ArdentHQ/arkscan/pull/803 (Laravel 10)

TODO:

- [x] Tests
- [x] Stan
- [x] Make events unique so there aren't multiple in the queue
- [x] Command to setup a webhook with a specific node
- [x] Secure URL to be used for webhooks - ties in with the command
- [x] Use [Laravel Reverb](https://laravel.com/docs/11.x/reverb) 
- [x] Look into SSL/TLS usage
- [x] Update testing steps below with reverb
- Future task - store webhook tokens for better management - https://app.clickup.com/t/86draxw85

Guides have been added for the setup of Websockets and Webhooks:

- [Websockets](https://github.com/ArdentHQ/arkscan/pull/781/files#diff-2a97a50aef8cc956a61d73483cb4cc2e80b348a337058b619095457333c208a2)
- [Webhooks](https://github.com/ArdentHQ/arkscan/pull/781/files#diff-7ed4490d4275cb22399d2b41968eedc8d2815199b719f1c4db92006ab2caedcc)

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by alfonsobries — APPROVED** [review]
I managed to make it work but had to play around with the .env configuration a bit for it to function. First, I ran the app with php artisan serve and opened the app from http://127.0.0.1:8000/ (and changed APP_URL=http://127.0.0.1:8000). (I couldn't get it to work with arkscan.test, but it could also be that I didn't find the right combination.)

I also defined these values differently from the example:

```
WEBSOCKETS_HOST=0.0.0.0
PUSHER_APP_HOST=127.0.0.1
PUSHER_APP_ALLOWED_ORIGINS=127.0.0.1
```

Note: Eventually, we'll need to add HTTPS to the websocket server in production. This can be achieved with a subdomain (instead of using a port). More details in this ticket -->.

**Review by alfonsobries — APPROVED** [review]

**Review by alfonsobries — COMMENTED** [review]
Mmm, apparently, Laravel WebSockets is no longer maintained in favor of Laravel Reverb. See https://github.com/beyondcode/laravel-websockets.

**Comment by alexbarnsley** [comment]
Reverb wasn't around when I did this PR, I've updated the description as we'll need to wait for https://github.com/ArdentHQ/arkscan/pull/803 (Laravel 10)

**Comment by ItsANameToo** [comment]
closing for now, can be reopened when we pick this up further

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
