### PR TITLE
refactor: search handling & flow

### PR DESCRIPTION
**Pull request by alexbarnsley**
## Summary

https://app.clickup.com/t/m95d2q

- The search page was too reliant on the SearchModule component which didn't make it easy for changes to be made, since the module was used for the search bar & additional options. It was easy enough to make the page use its own version of the search form
- Updated how searching works (based on the card) to search for Wallets > Transactions > Blocks in that order when using a basic search, otherwise a specific search is done if the advanced filters are open

**Note: tests are currently failing because the transaction search service also searched by block id. This either needs removing or the above order needs changing to Wallets > Blocks > Transactions**

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
When using the Advanced Search modal, search results return with "Not found", however, if you click search again on the search page it will then find what you're looking for. See video.

https://user-images.githubusercontent.com/44671015/183608590-3be4d261-58b9-4e6a-b13b-a4ea15e774bc.mov

**Review by samharperpittam — CHANGES_REQUESTED** [review]
When using the 'Advanced Search' and changing the type to Transaction, the modal seems to default a search to Block. See video

https://user-images.githubusercontent.com/44671015/183609074-1ae82326-ecfa-4c5f-8677-ecc35ffa922e.mov

**Review by samharperpittam — CHANGES_REQUESTED** [review]
When using the Advanced Search modal, it appears that any details added to search fields is ignored. Though, seems better when using the search in a page.

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Mici has no voters :sadup:
image

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
