### PR TITLE
feat: navbar search results

### PR DESCRIPTION
**Pull request by alexbarnsley**
## Summary

https://app.clickup.com/t/861mru5mf

Depends on https://github.com/ArkEcosystem/laravel-foundation/pull/569

todo:

- [x] tests & lints
- [x] mobile (if not split into another PR)

new todo
- [x] click on result behaviour
- [x] keyboard navigation
- [x] handle different type of transactions from designs
- [x] fix submit for mobile devices

## Checklist

-   [ ] I checked my UI changes against the design and there are no notable differences
-   [ ] I checked my UI changes for any responsiveness issues
-   [ ] I checked my UI changes in light AND dark mode
-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] I opened a corresponding card on Clickup for any remaining TODOs in my code
-   [ ] I added a short description on how to test this PR _(if necessary)_
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
When a delegate name is searched for, the address should be `gray-500`

Design
image


Imp
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Searching for just an address seems to show the address truncated when it doesn't need to be.

image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
eeek
image

`txID` = `78d748b6244facd38307da6cdd33278afa5311cdced88490adda149b16aa3b6e`

**Review by samharperpittam — CHANGES_REQUESTED** [review]
640 should have 32px of padding at the top and side of search
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
When searching for a transaction on mobile, the avatars can be different sizes
image

Txid = 784f6cfacf9472c03f735d2a75b952b880aafdbc06f59764b13cbc96ae5fcd99

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Multipayment transactions missing "Type" on mobile

Des
image


Imp
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
IPFS missing icon on mobile
Same with Delegate Registration
And Delegate Resignation
And Multisig
And Second Sig
And Switch Vote

image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Spec states a wallet's balance should be displayed with up to 8 decimal places. Currently this is set to 3. 

```
Show full ARK (for testnet DARK) balance with up to 8 decimal points
```

image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Search term not cleared on mobile

- Change to 375
- Open search
- Search for term (so search results are displayed)
- Click X button
- Search results not cleared

image

**Comment by alexbarnsley** [comment]
@samharperpittam I believe that last one is from the code I gave you for testing. When I removed that all seemed to be working okay. I've moved the address truncation for wallets out to a separate card - https://app.clickup.com/t/862jx9ymr

**Review by samharperpittam — APPROVED** [review]

**Pull request merged**
